
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'STATEMENTSEQUALS KEYWORD LPAREN NEWLINE NUMBER RPAREN STRING WHITESPACE\n        STATEMENTS : STATEMENT WHITESPACE STATEMENTS\n                   | STATEMENT\n        \n        STATEMENT : KEY EQUALS VALUE PARENTHESES\n                  | KEY EQUALS VALUE\n        \n        KEY : STRING\n            | NUMBER\n            | KEYWORD\n        VALUE   : KEYPARENTHESES : LPAREN STATEMENTS RPAREN'
    
_lr_action_items = {'RPAREN':([2,3,4,6,9,10,11,12,14,15,],[-7,-6,-2,-5,-1,-4,-8,-3,15,-9,]),'STRING':([0,7,8,13,],[6,6,6,6,]),'KEYWORD':([0,7,8,13,],[2,2,2,2,]),'EQUALS':([2,3,5,6,],[-7,-6,8,-5,]),'NUMBER':([0,7,8,13,],[3,3,3,3,]),'WHITESPACE':([2,3,4,6,10,11,12,15,],[-7,-6,7,-5,-4,-8,-3,-9,]),'LPAREN':([2,3,6,10,11,],[-7,-6,-5,13,-8,]),'$end':([1,2,3,4,6,9,10,11,12,15,],[0,-7,-6,-2,-5,-1,-4,-8,-3,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'VALUE':([8,],[10,]),'PARENTHESES':([10,],[12,]),'STATEMENTS':([0,7,13,],[1,9,14,]),'KEY':([0,7,8,13,],[5,5,11,5,]),'STATEMENT':([0,7,13,],[4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> STATEMENTS","S'",1,None,None,None),
  ('STATEMENTS -> STATEMENT WHITESPACE STATEMENTS','STATEMENTS',3,'p_STATEMENTS','SCLLexer.py',112),
  ('STATEMENTS -> STATEMENT','STATEMENTS',1,'p_STATEMENTS','SCLLexer.py',113),
  ('STATEMENT -> KEY EQUALS VALUE PARENTHESES','STATEMENT',4,'p_STATEMENT','SCLLexer.py',123),
  ('STATEMENT -> KEY EQUALS VALUE','STATEMENT',3,'p_STATEMENT','SCLLexer.py',124),
  ('KEY -> STRING','KEY',1,'p_KEY','SCLLexer.py',134),
  ('KEY -> NUMBER','KEY',1,'p_KEY','SCLLexer.py',135),
  ('KEY -> KEYWORD','KEY',1,'p_KEY','SCLLexer.py',136),
  ('VALUE -> KEY','VALUE',1,'p_VALUE','SCLLexer.py',142),
  ('PARENTHESES -> LPAREN STATEMENTS RPAREN','PARENTHESES',3,'p_PARENTHESES','SCLLexer.py',147),
]
